/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalAction = { 'reject' : null } |
  { 'approve' : null } |
  { 'sendBack' : null };
export interface ApprovalRecord {
  'action' : ApprovalAction,
  'approverRole' : CMSRole,
  'approver' : Principal,
  'timestamp' : Time,
  'comments' : string,
}
export type CMSRole = { 'informationSecurity' : null } |
  { 'implementationTeam' : null } |
  { 'changeReviewer' : null } |
  { 'changeRequester' : null } |
  { 'dataCenterHelpdesk' : null } |
  { 'changeApprover' : null };
export interface CRForm {
  'impacted' : string,
  'implementationPlan' : ExternalBlob,
  'endDate' : Time,
  'rollbackPlan' : ExternalBlob,
  'description' : string,
  'email' : string,
  'contactNumber' : string,
  'priority' : Priority,
  'requesterName' : string,
  'project' : string,
  'startDate' : Time,
  'reason' : string,
}
export interface ChangeRequest {
  'status' : ChangeRequestStatus,
  'requester' : Principal,
  'implementationDetails' : [] | [ImplementationDetails],
  'approvalHistory' : Array<ApprovalRecord>,
  'crId' : ChangeRequestId,
  'form' : CRForm,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'assignedTeam' : [] | [Principal],
}
export type ChangeRequestId = bigint;
export interface ChangeRequestPublicSummary {
  'status' : ChangeRequestStatus,
  'endDate' : Time,
  'crId' : ChangeRequestId,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'description' : string,
  'priority' : Priority,
  'requesterName' : string,
  'project' : string,
  'startDate' : Time,
  'reason' : string,
}
export type ChangeRequestStatus = { 'closed' : null } |
  { 'implStarted' : null } |
  { 'submitted' : null } |
  { 'underReview' : null } |
  { 'implDone' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface ImplementationDetails {
  'rcaDocument' : [] | [ExternalBlob],
  'actualEndTime' : [] | [Time],
  'success' : [] | [boolean],
  'remarks' : string,
  'actualStartTime' : [] | [Time],
}
export type Priority = { 'p1' : null } |
  { 'p2' : null } |
  { 'p3' : null };
export type Time = bigint;
export interface UserProfile {
  'cmsRole' : CMSRole,
  'name' : string,
  'email' : string,
  'contactNumber' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignImplementationTeam' : ActorMethod<
    [ChangeRequestId, Principal],
    undefined
  >,
  'closeChangeRequest' : ActorMethod<[ChangeRequestId], undefined>,
  'createChangeRequest' : ActorMethod<[CRForm], ChangeRequestId>,
  'getAllPublicChangeRequests' : ActorMethod<
    [],
    Array<ChangeRequestPublicSummary>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChangeRequestById' : ActorMethod<[ChangeRequestId], [] | [ChangeRequest]>,
  'getChangeRequestStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'successRate' : { 'successful' : bigint, 'failed' : bigint },
      'byStatus' : {
        'closed' : bigint,
        'implStarted' : bigint,
        'submitted' : bigint,
        'underReview' : bigint,
        'implDone' : bigint,
        'approved' : bigint,
        'rejected' : bigint,
      },
      'byPriority' : { 'p1' : bigint, 'p2' : bigint, 'p3' : bigint },
    }
  >,
  'getChangeRequestsByStatus' : ActorMethod<
    [ChangeRequestStatus],
    Array<ChangeRequestPublicSummary>
  >,
  'getRecentChangeRequests' : ActorMethod<
    [Time],
    Array<ChangeRequestPublicSummary>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processApproval' : ActorMethod<
    [ChangeRequestId, ApprovalAction, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateImplementationDetails' : ActorMethod<
    [ChangeRequestId, ImplementationDetails],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];