/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChangeRequestId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Priority = IDL.Variant({
  'p1' : IDL.Null,
  'p2' : IDL.Null,
  'p3' : IDL.Null,
});
export const CRForm = IDL.Record({
  'impacted' : IDL.Text,
  'implementationPlan' : ExternalBlob,
  'endDate' : Time,
  'rollbackPlan' : ExternalBlob,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'contactNumber' : IDL.Text,
  'priority' : Priority,
  'requesterName' : IDL.Text,
  'project' : IDL.Text,
  'startDate' : Time,
  'reason' : IDL.Text,
});
export const ChangeRequestStatus = IDL.Variant({
  'closed' : IDL.Null,
  'implStarted' : IDL.Null,
  'submitted' : IDL.Null,
  'underReview' : IDL.Null,
  'implDone' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ChangeRequestPublicSummary = IDL.Record({
  'status' : ChangeRequestStatus,
  'endDate' : Time,
  'crId' : ChangeRequestId,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'description' : IDL.Text,
  'priority' : Priority,
  'requesterName' : IDL.Text,
  'project' : IDL.Text,
  'startDate' : Time,
  'reason' : IDL.Text,
});
export const CMSRole = IDL.Variant({
  'informationSecurity' : IDL.Null,
  'implementationTeam' : IDL.Null,
  'changeReviewer' : IDL.Null,
  'changeRequester' : IDL.Null,
  'dataCenterHelpdesk' : IDL.Null,
  'changeApprover' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'cmsRole' : CMSRole,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'contactNumber' : IDL.Text,
  'department' : IDL.Text,
});
export const ImplementationDetails = IDL.Record({
  'rcaDocument' : IDL.Opt(ExternalBlob),
  'actualEndTime' : IDL.Opt(Time),
  'success' : IDL.Opt(IDL.Bool),
  'remarks' : IDL.Text,
  'actualStartTime' : IDL.Opt(Time),
});
export const ApprovalAction = IDL.Variant({
  'reject' : IDL.Null,
  'approve' : IDL.Null,
  'sendBack' : IDL.Null,
});
export const ApprovalRecord = IDL.Record({
  'action' : ApprovalAction,
  'approverRole' : CMSRole,
  'approver' : IDL.Principal,
  'timestamp' : Time,
  'comments' : IDL.Text,
});
export const ChangeRequest = IDL.Record({
  'status' : ChangeRequestStatus,
  'requester' : IDL.Principal,
  'implementationDetails' : IDL.Opt(ImplementationDetails),
  'approvalHistory' : IDL.Vec(ApprovalRecord),
  'crId' : ChangeRequestId,
  'form' : CRForm,
  'createdAt' : Time,
  'lastUpdated' : Time,
  'assignedTeam' : IDL.Opt(IDL.Principal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignImplementationTeam' : IDL.Func(
      [ChangeRequestId, IDL.Principal],
      [],
      [],
    ),
  'closeChangeRequest' : IDL.Func([ChangeRequestId], [], []),
  'createChangeRequest' : IDL.Func([CRForm], [ChangeRequestId], []),
  'getAllPublicChangeRequests' : IDL.Func(
      [],
      [IDL.Vec(ChangeRequestPublicSummary)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChangeRequestById' : IDL.Func(
      [ChangeRequestId],
      [IDL.Opt(ChangeRequest)],
      ['query'],
    ),
  'getChangeRequestStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'successRate' : IDL.Record({
            'successful' : IDL.Nat,
            'failed' : IDL.Nat,
          }),
          'byStatus' : IDL.Record({
            'closed' : IDL.Nat,
            'implStarted' : IDL.Nat,
            'submitted' : IDL.Nat,
            'underReview' : IDL.Nat,
            'implDone' : IDL.Nat,
            'approved' : IDL.Nat,
            'rejected' : IDL.Nat,
          }),
          'byPriority' : IDL.Record({
            'p1' : IDL.Nat,
            'p2' : IDL.Nat,
            'p3' : IDL.Nat,
          }),
        }),
      ],
      ['query'],
    ),
  'getChangeRequestsByStatus' : IDL.Func(
      [ChangeRequestStatus],
      [IDL.Vec(ChangeRequestPublicSummary)],
      ['query'],
    ),
  'getRecentChangeRequests' : IDL.Func(
      [Time],
      [IDL.Vec(ChangeRequestPublicSummary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processApproval' : IDL.Func(
      [ChangeRequestId, ApprovalAction, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateImplementationDetails' : IDL.Func(
      [ChangeRequestId, ImplementationDetails],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChangeRequestId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Priority = IDL.Variant({
    'p1' : IDL.Null,
    'p2' : IDL.Null,
    'p3' : IDL.Null,
  });
  const CRForm = IDL.Record({
    'impacted' : IDL.Text,
    'implementationPlan' : ExternalBlob,
    'endDate' : Time,
    'rollbackPlan' : ExternalBlob,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'contactNumber' : IDL.Text,
    'priority' : Priority,
    'requesterName' : IDL.Text,
    'project' : IDL.Text,
    'startDate' : Time,
    'reason' : IDL.Text,
  });
  const ChangeRequestStatus = IDL.Variant({
    'closed' : IDL.Null,
    'implStarted' : IDL.Null,
    'submitted' : IDL.Null,
    'underReview' : IDL.Null,
    'implDone' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ChangeRequestPublicSummary = IDL.Record({
    'status' : ChangeRequestStatus,
    'endDate' : Time,
    'crId' : ChangeRequestId,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'description' : IDL.Text,
    'priority' : Priority,
    'requesterName' : IDL.Text,
    'project' : IDL.Text,
    'startDate' : Time,
    'reason' : IDL.Text,
  });
  const CMSRole = IDL.Variant({
    'informationSecurity' : IDL.Null,
    'implementationTeam' : IDL.Null,
    'changeReviewer' : IDL.Null,
    'changeRequester' : IDL.Null,
    'dataCenterHelpdesk' : IDL.Null,
    'changeApprover' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'cmsRole' : CMSRole,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'contactNumber' : IDL.Text,
    'department' : IDL.Text,
  });
  const ImplementationDetails = IDL.Record({
    'rcaDocument' : IDL.Opt(ExternalBlob),
    'actualEndTime' : IDL.Opt(Time),
    'success' : IDL.Opt(IDL.Bool),
    'remarks' : IDL.Text,
    'actualStartTime' : IDL.Opt(Time),
  });
  const ApprovalAction = IDL.Variant({
    'reject' : IDL.Null,
    'approve' : IDL.Null,
    'sendBack' : IDL.Null,
  });
  const ApprovalRecord = IDL.Record({
    'action' : ApprovalAction,
    'approverRole' : CMSRole,
    'approver' : IDL.Principal,
    'timestamp' : Time,
    'comments' : IDL.Text,
  });
  const ChangeRequest = IDL.Record({
    'status' : ChangeRequestStatus,
    'requester' : IDL.Principal,
    'implementationDetails' : IDL.Opt(ImplementationDetails),
    'approvalHistory' : IDL.Vec(ApprovalRecord),
    'crId' : ChangeRequestId,
    'form' : CRForm,
    'createdAt' : Time,
    'lastUpdated' : Time,
    'assignedTeam' : IDL.Opt(IDL.Principal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignImplementationTeam' : IDL.Func(
        [ChangeRequestId, IDL.Principal],
        [],
        [],
      ),
    'closeChangeRequest' : IDL.Func([ChangeRequestId], [], []),
    'createChangeRequest' : IDL.Func([CRForm], [ChangeRequestId], []),
    'getAllPublicChangeRequests' : IDL.Func(
        [],
        [IDL.Vec(ChangeRequestPublicSummary)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChangeRequestById' : IDL.Func(
        [ChangeRequestId],
        [IDL.Opt(ChangeRequest)],
        ['query'],
      ),
    'getChangeRequestStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'successRate' : IDL.Record({
              'successful' : IDL.Nat,
              'failed' : IDL.Nat,
            }),
            'byStatus' : IDL.Record({
              'closed' : IDL.Nat,
              'implStarted' : IDL.Nat,
              'submitted' : IDL.Nat,
              'underReview' : IDL.Nat,
              'implDone' : IDL.Nat,
              'approved' : IDL.Nat,
              'rejected' : IDL.Nat,
            }),
            'byPriority' : IDL.Record({
              'p1' : IDL.Nat,
              'p2' : IDL.Nat,
              'p3' : IDL.Nat,
            }),
          }),
        ],
        ['query'],
      ),
    'getChangeRequestsByStatus' : IDL.Func(
        [ChangeRequestStatus],
        [IDL.Vec(ChangeRequestPublicSummary)],
        ['query'],
      ),
    'getRecentChangeRequests' : IDL.Func(
        [Time],
        [IDL.Vec(ChangeRequestPublicSummary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processApproval' : IDL.Func(
        [ChangeRequestId, ApprovalAction, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateImplementationDetails' : IDL.Func(
        [ChangeRequestId, ImplementationDetails],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };