/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    cmsRole: CMSRole;
    name: string;
    email: string;
    contactNumber: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ChangeRequestPublicSummary {
    status: ChangeRequestStatus;
    endDate: Time;
    crId: ChangeRequestId;
    createdAt: Time;
    lastUpdated: Time;
    description: string;
    priority: Priority;
    requesterName: string;
    project: string;
    startDate: Time;
    reason: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ApprovalRecord {
    action: ApprovalAction;
    approverRole: CMSRole;
    approver: Principal;
    timestamp: Time;
    comments: string;
}
export interface ChangeRequest {
    status: ChangeRequestStatus;
    requester: Principal;
    implementationDetails?: ImplementationDetails;
    approvalHistory: Array<ApprovalRecord>;
    crId: ChangeRequestId;
    form: CRForm;
    createdAt: Time;
    lastUpdated: Time;
    assignedTeam?: Principal;
}
export interface ImplementationDetails {
    rcaDocument?: ExternalBlob;
    actualEndTime?: Time;
    success?: boolean;
    remarks: string;
    actualStartTime?: Time;
}
export type ChangeRequestId = bigint;
export interface CRForm {
    impacted: string;
    implementationPlan: ExternalBlob;
    endDate: Time;
    rollbackPlan: ExternalBlob;
    description: string;
    email: string;
    contactNumber: string;
    priority: Priority;
    requesterName: string;
    project: string;
    startDate: Time;
    reason: string;
}
export enum ApprovalAction {
    reject = "reject",
    approve = "approve",
    sendBack = "sendBack"
}
export enum CMSRole {
    informationSecurity = "informationSecurity",
    implementationTeam = "implementationTeam",
    changeReviewer = "changeReviewer",
    changeRequester = "changeRequester",
    dataCenterHelpdesk = "dataCenterHelpdesk",
    changeApprover = "changeApprover"
}
export enum ChangeRequestStatus {
    closed = "closed",
    implStarted = "implStarted",
    submitted = "submitted",
    underReview = "underReview",
    implDone = "implDone",
    approved = "approved",
    rejected = "rejected"
}
export enum Priority {
    p1 = "p1",
    p2 = "p2",
    p3 = "p3"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignImplementationTeam(crId: ChangeRequestId, teamMember: Principal): Promise<void>;
    closeChangeRequest(crId: ChangeRequestId): Promise<void>;
    createChangeRequest(form: CRForm): Promise<ChangeRequestId>;
    getAllPublicChangeRequests(): Promise<Array<ChangeRequestPublicSummary>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChangeRequestById(crId: ChangeRequestId): Promise<ChangeRequest | null>;
    getChangeRequestStats(): Promise<{
        total: bigint;
        successRate: {
            successful: bigint;
            failed: bigint;
        };
        byStatus: {
            closed: bigint;
            implStarted: bigint;
            submitted: bigint;
            underReview: bigint;
            implDone: bigint;
            approved: bigint;
            rejected: bigint;
        };
        byPriority: {
            p1: bigint;
            p2: bigint;
            p3: bigint;
        };
    }>;
    getChangeRequestsByStatus(status: ChangeRequestStatus): Promise<Array<ChangeRequestPublicSummary>>;
    getRecentChangeRequests(timestamp: Time): Promise<Array<ChangeRequestPublicSummary>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    processApproval(crId: ChangeRequestId, action: ApprovalAction, comments: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateImplementationDetails(crId: ChangeRequestId, details: ImplementationDetails): Promise<void>;
}
import type { ApprovalAction as _ApprovalAction, ApprovalRecord as _ApprovalRecord, CMSRole as _CMSRole, CRForm as _CRForm, ChangeRequest as _ChangeRequest, ChangeRequestId as _ChangeRequestId, ChangeRequestPublicSummary as _ChangeRequestPublicSummary, ChangeRequestStatus as _ChangeRequestStatus, ExternalBlob as _ExternalBlob, ImplementationDetails as _ImplementationDetails, Priority as _Priority, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignImplementationTeam(arg0: ChangeRequestId, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignImplementationTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignImplementationTeam(arg0, arg1);
            return result;
        }
    }
    async closeChangeRequest(arg0: ChangeRequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeChangeRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeChangeRequest(arg0);
            return result;
        }
    }
    async createChangeRequest(arg0: CRForm): Promise<ChangeRequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.createChangeRequest(await to_candid_CRForm_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChangeRequest(await to_candid_CRForm_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllPublicChangeRequests(): Promise<Array<ChangeRequestPublicSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicChangeRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicChangeRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChangeRequestById(arg0: ChangeRequestId): Promise<ChangeRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeRequestById(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeRequestById(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChangeRequestStats(): Promise<{
        total: bigint;
        successRate: {
            successful: bigint;
            failed: bigint;
        };
        byStatus: {
            closed: bigint;
            implStarted: bigint;
            submitted: bigint;
            underReview: bigint;
            implDone: bigint;
            approved: bigint;
            rejected: bigint;
        };
        byPriority: {
            p1: bigint;
            p2: bigint;
            p3: bigint;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeRequestStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeRequestStats();
            return result;
        }
    }
    async getChangeRequestsByStatus(arg0: ChangeRequestStatus): Promise<Array<ChangeRequestPublicSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeRequestsByStatus(to_candid_ChangeRequestStatus_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeRequestsByStatus(to_candid_ChangeRequestStatus_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentChangeRequests(arg0: Time): Promise<Array<ChangeRequestPublicSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentChangeRequests(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentChangeRequests(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async processApproval(arg0: ChangeRequestId, arg1: ApprovalAction, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processApproval(arg0, to_candid_ApprovalAction_n50(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processApproval(arg0, to_candid_ApprovalAction_n50(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateImplementationDetails(arg0: ChangeRequestId, arg1: ImplementationDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateImplementationDetails(arg0, await to_candid_ImplementationDetails_n56(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateImplementationDetails(arg0, await to_candid_ImplementationDetails_n56(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalAction_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalAction): ApprovalAction {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalRecord_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalRecord): ApprovalRecord {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_CMSRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CMSRole): CMSRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_CRForm_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CRForm): Promise<CRForm> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ChangeRequestPublicSummary_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChangeRequestPublicSummary): ChangeRequestPublicSummary {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ChangeRequestStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChangeRequestStatus): ChangeRequestStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ChangeRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChangeRequest): Promise<ChangeRequest> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ImplementationDetails_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImplementationDetails): Promise<ImplementationDetails> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChangeRequest]): Promise<ChangeRequest | null> {
    return value.length === 0 ? null : await from_candid_ChangeRequest_n32(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImplementationDetails]): Promise<ImplementationDetails | null> {
    return value.length === 0 ? null : await from_candid_ImplementationDetails_n35(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ChangeRequestStatus;
    endDate: _Time;
    crId: _ChangeRequestId;
    createdAt: _Time;
    lastUpdated: _Time;
    description: string;
    priority: _Priority;
    requesterName: string;
    project: string;
    startDate: _Time;
    reason: string;
}): {
    status: ChangeRequestStatus;
    endDate: Time;
    crId: ChangeRequestId;
    createdAt: Time;
    lastUpdated: Time;
    description: string;
    priority: Priority;
    requesterName: string;
    project: string;
    startDate: Time;
    reason: string;
} {
    return {
        status: from_candid_ChangeRequestStatus_n18(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        crId: value.crId,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        description: value.description,
        priority: from_candid_Priority_n20(_uploadFile, _downloadFile, value.priority),
        requesterName: value.requesterName,
        project: value.project,
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cmsRole: _CMSRole;
    name: string;
    email: string;
    contactNumber: string;
    department: string;
}): {
    cmsRole: CMSRole;
    name: string;
    email: string;
    contactNumber: string;
    department: string;
} {
    return {
        cmsRole: from_candid_CMSRole_n26(_uploadFile, _downloadFile, value.cmsRole),
        name: value.name,
        email: value.email,
        contactNumber: value.contactNumber,
        department: value.department
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ChangeRequestStatus;
    requester: Principal;
    implementationDetails: [] | [_ImplementationDetails];
    approvalHistory: Array<_ApprovalRecord>;
    crId: _ChangeRequestId;
    form: _CRForm;
    createdAt: _Time;
    lastUpdated: _Time;
    assignedTeam: [] | [Principal];
}): Promise<{
    status: ChangeRequestStatus;
    requester: Principal;
    implementationDetails?: ImplementationDetails;
    approvalHistory: Array<ApprovalRecord>;
    crId: ChangeRequestId;
    form: CRForm;
    createdAt: Time;
    lastUpdated: Time;
    assignedTeam?: Principal;
}> {
    return {
        status: from_candid_ChangeRequestStatus_n18(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        implementationDetails: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.implementationDetails)),
        approvalHistory: from_candid_vec_n40(_uploadFile, _downloadFile, value.approvalHistory),
        crId: value.crId,
        form: await from_candid_CRForm_n45(_uploadFile, _downloadFile, value.form),
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        assignedTeam: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.assignedTeam))
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rcaDocument: [] | [_ExternalBlob];
    actualEndTime: [] | [_Time];
    success: [] | [boolean];
    remarks: string;
    actualStartTime: [] | [_Time];
}): Promise<{
    rcaDocument?: ExternalBlob;
    actualEndTime?: Time;
    success?: boolean;
    remarks: string;
    actualStartTime?: Time;
}> {
    return {
        rcaDocument: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.rcaDocument)),
        actualEndTime: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.actualEndTime)),
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        remarks: value.remarks,
        actualStartTime: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.actualStartTime))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: _ApprovalAction;
    approverRole: _CMSRole;
    approver: Principal;
    timestamp: _Time;
    comments: string;
}): {
    action: ApprovalAction;
    approverRole: CMSRole;
    approver: Principal;
    timestamp: Time;
    comments: string;
} {
    return {
        action: from_candid_ApprovalAction_n43(_uploadFile, _downloadFile, value.action),
        approverRole: from_candid_CMSRole_n26(_uploadFile, _downloadFile, value.approverRole),
        approver: value.approver,
        timestamp: value.timestamp,
        comments: value.comments
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    impacted: string;
    implementationPlan: _ExternalBlob;
    endDate: _Time;
    rollbackPlan: _ExternalBlob;
    description: string;
    email: string;
    contactNumber: string;
    priority: _Priority;
    requesterName: string;
    project: string;
    startDate: _Time;
    reason: string;
}): Promise<{
    impacted: string;
    implementationPlan: ExternalBlob;
    endDate: Time;
    rollbackPlan: ExternalBlob;
    description: string;
    email: string;
    contactNumber: string;
    priority: Priority;
    requesterName: string;
    project: string;
    startDate: Time;
    reason: string;
}> {
    return {
        impacted: value.impacted,
        implementationPlan: await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value.implementationPlan),
        endDate: value.endDate,
        rollbackPlan: await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value.rollbackPlan),
        description: value.description,
        email: value.email,
        contactNumber: value.contactNumber,
        priority: from_candid_Priority_n20(_uploadFile, _downloadFile, value.priority),
        requesterName: value.requesterName,
        project: value.project,
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    implStarted: null;
} | {
    submitted: null;
} | {
    underReview: null;
} | {
    implDone: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ChangeRequestStatus {
    return "closed" in value ? ChangeRequestStatus.closed : "implStarted" in value ? ChangeRequestStatus.implStarted : "submitted" in value ? ChangeRequestStatus.submitted : "underReview" in value ? ChangeRequestStatus.underReview : "implDone" in value ? ChangeRequestStatus.implDone : "approved" in value ? ChangeRequestStatus.approved : "rejected" in value ? ChangeRequestStatus.rejected : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    p1: null;
} | {
    p2: null;
} | {
    p3: null;
}): Priority {
    return "p1" in value ? Priority.p1 : "p2" in value ? Priority.p2 : "p3" in value ? Priority.p3 : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    informationSecurity: null;
} | {
    implementationTeam: null;
} | {
    changeReviewer: null;
} | {
    changeRequester: null;
} | {
    dataCenterHelpdesk: null;
} | {
    changeApprover: null;
}): CMSRole {
    return "informationSecurity" in value ? CMSRole.informationSecurity : "implementationTeam" in value ? CMSRole.implementationTeam : "changeReviewer" in value ? CMSRole.changeReviewer : "changeRequester" in value ? CMSRole.changeRequester : "dataCenterHelpdesk" in value ? CMSRole.dataCenterHelpdesk : "changeApprover" in value ? CMSRole.changeApprover : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reject: null;
} | {
    approve: null;
} | {
    sendBack: null;
}): ApprovalAction {
    return "reject" in value ? ApprovalAction.reject : "approve" in value ? ApprovalAction.approve : "sendBack" in value ? ApprovalAction.sendBack : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChangeRequestPublicSummary>): Array<ChangeRequestPublicSummary> {
    return value.map((x)=>from_candid_ChangeRequestPublicSummary_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovalRecord>): Array<ApprovalRecord> {
    return value.map((x)=>from_candid_ApprovalRecord_n41(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalAction_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalAction): _ApprovalAction {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_CMSRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CMSRole): _CMSRole {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
async function to_candid_CRForm_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CRForm): Promise<_CRForm> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ChangeRequestStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChangeRequestStatus): _ChangeRequestStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ImplementationDetails_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImplementationDetails): Promise<_ImplementationDetails> {
    return await to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    impacted: string;
    implementationPlan: ExternalBlob;
    endDate: Time;
    rollbackPlan: ExternalBlob;
    description: string;
    email: string;
    contactNumber: string;
    priority: Priority;
    requesterName: string;
    project: string;
    startDate: Time;
    reason: string;
}): Promise<{
    impacted: string;
    implementationPlan: _ExternalBlob;
    endDate: _Time;
    rollbackPlan: _ExternalBlob;
    description: string;
    email: string;
    contactNumber: string;
    priority: _Priority;
    requesterName: string;
    project: string;
    startDate: _Time;
    reason: string;
}> {
    return {
        impacted: value.impacted,
        implementationPlan: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.implementationPlan),
        endDate: value.endDate,
        rollbackPlan: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.rollbackPlan),
        description: value.description,
        email: value.email,
        contactNumber: value.contactNumber,
        priority: to_candid_Priority_n13(_uploadFile, _downloadFile, value.priority),
        requesterName: value.requesterName,
        project: value.project,
        startDate: value.startDate,
        reason: value.reason
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cmsRole: CMSRole;
    name: string;
    email: string;
    contactNumber: string;
    department: string;
}): {
    cmsRole: _CMSRole;
    name: string;
    email: string;
    contactNumber: string;
    department: string;
} {
    return {
        cmsRole: to_candid_CMSRole_n54(_uploadFile, _downloadFile, value.cmsRole),
        name: value.name,
        email: value.email,
        contactNumber: value.contactNumber,
        department: value.department
    };
}
async function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rcaDocument?: ExternalBlob;
    actualEndTime?: Time;
    success?: boolean;
    remarks: string;
    actualStartTime?: Time;
}): Promise<{
    rcaDocument: [] | [_ExternalBlob];
    actualEndTime: [] | [_Time];
    success: [] | [boolean];
    remarks: string;
    actualStartTime: [] | [_Time];
}> {
    return {
        rcaDocument: value.rcaDocument ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.rcaDocument)) : candid_none(),
        actualEndTime: value.actualEndTime ? candid_some(value.actualEndTime) : candid_none(),
        success: value.success ? candid_some(value.success) : candid_none(),
        remarks: value.remarks,
        actualStartTime: value.actualStartTime ? candid_some(value.actualStartTime) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    p1: null;
} | {
    p2: null;
} | {
    p3: null;
} {
    return value == Priority.p1 ? {
        p1: null
    } : value == Priority.p2 ? {
        p2: null
    } : value == Priority.p3 ? {
        p3: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChangeRequestStatus): {
    closed: null;
} | {
    implStarted: null;
} | {
    submitted: null;
} | {
    underReview: null;
} | {
    implDone: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ChangeRequestStatus.closed ? {
        closed: null
    } : value == ChangeRequestStatus.implStarted ? {
        implStarted: null
    } : value == ChangeRequestStatus.submitted ? {
        submitted: null
    } : value == ChangeRequestStatus.underReview ? {
        underReview: null
    } : value == ChangeRequestStatus.implDone ? {
        implDone: null
    } : value == ChangeRequestStatus.approved ? {
        approved: null
    } : value == ChangeRequestStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalAction): {
    reject: null;
} | {
    approve: null;
} | {
    sendBack: null;
} {
    return value == ApprovalAction.reject ? {
        reject: null
    } : value == ApprovalAction.approve ? {
        approve: null
    } : value == ApprovalAction.sendBack ? {
        sendBack: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CMSRole): {
    informationSecurity: null;
} | {
    implementationTeam: null;
} | {
    changeReviewer: null;
} | {
    changeRequester: null;
} | {
    dataCenterHelpdesk: null;
} | {
    changeApprover: null;
} {
    return value == CMSRole.informationSecurity ? {
        informationSecurity: null
    } : value == CMSRole.implementationTeam ? {
        implementationTeam: null
    } : value == CMSRole.changeReviewer ? {
        changeReviewer: null
    } : value == CMSRole.changeRequester ? {
        changeRequester: null
    } : value == CMSRole.dataCenterHelpdesk ? {
        dataCenterHelpdesk: null
    } : value == CMSRole.changeApprover ? {
        changeApprover: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
